### ISSUE TITLE
TypeError: Runtime.getFunctions is not a function

### ISSUE THREAD

**Issue by jsjoeio** [dkundel/twilio-run#9]
Hi 👋 !

First, thank you for creating this! I'm excited to see it in action! 😄 

However, I'm not sure what I'm doing wrong. I'm getting the following error when running `twilio-run` in the CLI. I also tried installing `twilio-run` as a global dependency but that didn't change anything.

```javascript
/Users/joeprevite/Dev/learning/twilio-run-test/node_modules/twilio-run/src/cli/route-info.js:10
  const functions = Runtime.getFunctions();
                            ^

TypeError: Runtime.getFunctions is not a function
    at getRouteInfo (/Users/joeprevite/Dev/learning/twilio-run-test/node_modules/twilio-run/src/cli/route-info.js:10:29)
    at Server.app.listen (/Users/joeprevite/Dev/learning/twilio-run-test/node_modules/twilio-run/src/cli.js:30:20)
    at Object.onceWrapper (events.js:273:13)
    at Server.emit (events.js:182:13)
    at emitListeningNT (net.js:1370:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

### Expected behavior
Based on the documentation, when I run `twilio-run` or more specifically `node_modules/.bin/twilio-run` while inside the root directory, it should look for a sub-directory titled `functions` then find all my functions in there and run them. 

### Actual behavior
It throws an error. ^See code block above.

### Steps to reproduce the behavior
1. Clone this [repository](https://github.com/jsjoeio/twilio-run-test)
2. Run `npm install`
3. Run `node_modules/.bin/twilio-run`

For some reason, it seems like `getFunctions()` is not being returned on the `Runtime` object in `/twilio-run/src/cli/route-info.js`. 🤔 

Happy to help try and solve this (with some guidance) if you'd like.

**Comment by dkundel** [comment]
Thank you so much for catching this. There are no tests for that file so they didn't catch the "fix" that I introduced for #7
